id: configure_apikey
hints:
- On the New Relic one platform, click on your avatar on the top right corner, then click API Keys
- On the API Keys screen, click `Create a key`
- Once a key is generated, click the three dots next to it and then click on `Copy key`
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: Time to commence the observing!
      - text: Just one thing before you begin observing others — I want to observe you more closely. All you need to do is **give me an API key** for your account. 
        delay: 1500
      - text: Its type should be **`USER`,** and you can find the instructions for **generating one** [here](https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/).\n**Ping me with the key** when you have generated it.
        delay: 2500
trigger:
  type: user_message_to_devops
  flowNode:
    do:
    - actionId: newrelic_configure_with_key
      name: newrelic_configure_with_key
      params:
        newRelicKey: ${userMessageText}
    if:
      conditions:
      - conditionId: action_success
        params:
          name: newrelic_configure_with_key
      then:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: Do you feel seen? Because you are! Good job, now let’s move on.
              delay: 2500
        - actionId: finish_step
      else:
        switch:
          key: ${outputs.newrelic_configure_with_key.error}
          cases:
            invalid_key_format:
              do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                  - text: This isn’t an API key, so why are you bothering me with it?
                    delay: 2000
            invalid_key:
              do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                  - text: Looks like an API key alright, but it ain't the right one. Try again.
                    delay: 2000
