id: create_secret
learningObjectives:
  - Connecting a cloud app to New Relic
hints:
  - Use the license key generated in the configuration file you’ve just downloaded.
  - You can also find the license key in the [New Relic platform](https://one.newrelic.com/api-keys), make sure to use a key with type `INGEST - LICENSE`
  - For help with creating a secret, you can try this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)
startFlow:
  if:
    conditions:
      - conditionId: k8s_backend_config_var_defined
        name: new_relic_license_key_config
        params:
          key: NEW_RELIC_LICENSE_KEY
      - conditionId: newrelic_license_key_valid
        params:
          licenseKey: ${outputs.new_relic_license_key_config.value}
      - conditionId: k8s_backend_config_var_defined
        params:
          key: NEW_RELIC_APP_NAME
    then:
      do:
        - actionId: bot_message
          params:
            person: devops
            messages:
              - text: Great job, looks like you’ve already configured everything. Our application should start sending data to New Relic shortly.
                delay: 1500
        - actionId: finish_step
    else:
      do:
        - actionId: bot_message
          params:
            person: devops
            messages:
              - text: Now we need to set the New Relic environment variables in our backend pods, so the agent can start properly and send data to New Relic.
                delay: 0
              - text: We should start by creating a secret to hold our New Relic API key
                delay: 1000
              - text: You can use the following command to do so - `kubectl create secret generic my-secret --from-literal=my_secret=my_value`
                delay: 1000
              - text: Let's call the first secret `new-relic-license-key`, which will store our `INGEST` API key"
                delay: 1000
              - text: Tell me when you're done
                delay: 1000
trigger:
  type: user_message
  params:
    person: devops
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        if:
          conditions:
            - conditionId: k8s_secret_defined
              params:
                secretName: new-relic-license-key
          then:
            do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                    - text: Great I see you've created the secret.
                      delay: 1700
              - actionId: finish_step
          else:
            do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                    - text: Are you sure you've create a key named `new-relic-license-key`?
                      delay: 700
      else:
        do:
          - actionId: bot_message
            params:
              person: devops
              messages:
                - text: Umm, If you need any help, just let me know that you’re stuck. If that’s not the case - take your time and tell me once you're ready :)
                  delay: 2000