id: newrelic_observability_configure_agent
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
    paramsFramework:
      node:
        messages:
        - text: "Now it’s really time to add New Relic to your **backend** Heroku app."
          delay: 1000
        - text: "It’s a relatively straightforward process, that begins [here](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent/)."
          delay: 1700
        - text: "Follow the “Install the Node.js agent” instructions and when you’re done, **open a PR** and I’ll take a look."
          delay: 1000
        - text: "Oh and by the way - we're using **\`yarn\`** and not \`npm\`."
          delay: 1300
      rails:
        messages:
        - text: "Now it’s really time to add New Relic to your **backend** Heroku app."
          delay: 1000
        - text: "It’s a relatively straightforward process, that begins [here](https://docs.newrelic.com/docs/apm/agents/ruby-agent/installation/install-new-relic-ruby-agent#Installing_the_Gem)."
          delay: 1500
        - text: "Follow the “Install the gem” and then “Install the configuration file” instructions, and when you’re done, **open a PR** and I’ll take a look."
          delay: 1000
      python:
        messages:
        - text: "Now it’s really time to add New Relic to your **backend** Heroku app."
          delay: 1000
        - text: "It’s a relatively straightforward process, that begins [here](https://docs.newrelic.com/docs/apm/agents/python-agent/installation/standard-python-agent-install/#install)."
          delay: 1500
        - text: "Follow the “Standard Python agent install” instructions.\n\nOh and by the way - we're using **\`poetry\`** and not \`pip\` directly. Instead of the part that says \`pip install newrelic\` be sure to use the \`poetry add newrelic\` command for adding a new package.\n\nAlso, once you have it installed, you should stop \`docker-compose\` and then rerun it to have it update the appropriate `requirements.txt` file.\n\nFinally, make sure you update how we run the app in Heroku (hint: look at the `Procfile` in the repository) and make sure you add the necessary New Relic admin script command, as per their instructions.\n\nWhen you’re done, **open a PR** and I’ll take a look."
          delay: 3000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${githubPrLifecycleStatus}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: devops
              messages:
              - text: Checking now
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: devops
              message: Checking now.
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_is_file_modified
              params:
                defaultResult: true
              paramsFramework:
                node:
                  fileName: backend/app.js
            then:
              if:
                conditions:
                - conditionId: github_is_file_modified
                  params:
                    defaultResult: true
                  paramsFramework:
                    python:
                      fileName: backend/Procfile
                then:
                  if:
                    conditions:
                    - conditionId: github_is_file_modified
                      params:
                        defaultResult: true
                      paramsFramework:
                        node:
                          fileName: backend/package.json
                        rails:
                          fileName: backend/Gemfile
                        python:
                          fileName: backend/requirements.txt
                    then:
                      if:
                        conditions:
                        - conditionId: github_is_file_added
                          params:
                            defaultResult: true
                          paramsFramework:
                            node:
                              fileName: backend/newrelic.js
                            rails:
                              fileName: backend/config/newrelic.yml
                            python:
                              fileName: backend/newrelic.ini
                        then:
                          if:
                            conditions:
                            - conditionId: github_is_file_contains
                              params:
                                regex: license_key
                                defaultResult: false
                              paramsFramework:
                                node:
                                  fileName: backend/newrelic.js
                                rails:
                                  fileName: backend/config/newrelic.yml
                                python:
                                  fileName: backend/newrelic.ini
                            then:
                              do:
                              - actionId: bot_message
                                params:
                                  person: devops
                                  messages:
                                  - text: "I see you've committed a license key to Git. Shouldn't do that, security-wise. Please remove the entire property from the config file, we'll add it as an environment variable."
                                    delay: 1000
                              - actionId: github_pr_reject
                                params:
                                  person: devops
                                  message: "I see you've committed a license key to Git. Shouldn't do that, security-wise. Please remove the entire property from the config file, we'll add it as an environment variable."
                                  messageName: committed_license_key
                            else:
                              if:
                                conditions:
                                - conditionId: github_is_file_added
                                  params:
                                    defaultResult: false
                                  paramsFramework:
                                    node:
                                      fileName: backend/package-lock.json
                                then:
                                  do:
                                  - actionId: bot_message
                                    params:
                                      person: devops
                                      messages:
                                      - text: "I see you have both \`package-lock.json\` and \`yarn.lock\`. This can cause issues in the build. Let’s stick with just yarn for now, and remove the \`package-lock.json\`."
                                        delay: 1000
                                  - actionId: github_pr_reject
                                    params:
                                      person: devops
                                      message: " I see you have both \`package-lock.json\` and \`yarn.lock\`. This can cause issues in the build. Let’s stick with just yarn for now, and remove the \`package-lock.json\`."
                                      messageName: npm_lock_added
                                else:
                                  do:
                                  - actionId: bot_message
                                    params:
                                      person: devops
                                      messages:
                                      - text: "Looking good! You can merge the PR now."
                                        delay: 1000
                                  - actionId: github_pr_approve
                                    params:
                                      person: devops
                                      message: "Looking good! You can merge the PR now."
                        else:
                          do:
                          - actionId: bot_message
                            params:
                              person: devops
                              messages:
                              - text: "I don’t see a New Relic config file. Won’t work without it."
                                delay: 1000
                          - actionId: github_pr_reject
                            params:
                              person: devops
                              message: "I don’t see a New Relic config file. Won’t work without it."
                              messageName: missing_config
                    else:
                      do:
                      - actionId: bot_message
                        params:
                          person: devops
                          messages:
                          - text: "Did you add the New Relic package to the dependency list? Make sure to add it to the **backend** project"
                            delay: 1000
                      - actionId: github_pr_reject
                        params:
                          person: devops
                          message: "Did you add the New Relic package to the dependency list? Make sure to add it to the **backend** project"
                          messageName: missing_dependency
                else:
                  do:
                  - actionId: bot_message
                    params:
                      person: devops
                      messages:
                      - text: "Looks like you did not update the \`Procfile\`. Remember you need to add the New Relic admin script command in front of your usual startup command options."
                        delay: 1000
                  - actionId: github_pr_reject
                    params:
                      person: devops
                      message: "Looks like you did not update the \`Procfile\`. Remember you need to add the New Relic admin script command in front of your usual startup command options."
                      messageName: procfile_not_updated
            else:
              do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                  - text: "Did you make sure you added the \`require\` statement to the main app file?"
                    delay: 1000
              - actionId: github_pr_reject
                params:
                  person: devops
                  message: "Did you make sure you added the \`require\` statement to the main app file?"
                  messageName: missing_require
        github_pr_merged:
          do:
          - actionId: finish_step
