id: newrelic_observability_open_account
hints:
- You can sign up for New Relic <https://newrelic.com/signup|here>
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "So, we are being watched. You know that, right? All of us, by numerous parties"
        delay: 2000
      - text: "**Isn’t it great?**"
        delay: 3000
      - text: "I, for once, sleep better knowing that if something happens, someone will be notified. What can happen and who will be notified? It doesn’t really matter to me!"
        delay: 2500
      - text: "And now, you might get to play the part of an observer as well, because we have a production system that needs you - to understand whether it functions properly."
        delay: 3500
      - text: "So we have the system itself set up, as a Heroku app. Here’s a link to the frontend, if you don’t believe it exists -  ${user.frontendHerokuAppUrl}. There’s also an **invite in your mail** to both the front and backend apps, which you need to **accept**."
        delay: 3500
      - text: "Now, all that’s left for you to do is connect observability tools to it. The first step you need to do is [open a New Relic account](https://newrelic.com/). Do that, and **tell me when you’re done**.  Oh, and if you’re wondering, all you need is the account — **no reason to proceed with the installation** plan."
        delay: 2500
trigger:
  type: user_message_to_devops
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: 'Cool. Moving on.'
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: " Umm, If you need any help, just let me know that you’re stuck. If that’s not the case - take your time and tell me once you're ready :)"
              delay: 2000
